"use client";
import {useEffect,useMemo,useState} from "react";
import {getSupabaseBrowserClient} from "@/lib/supabase-browser";
type Order={id:string;customer_name:string;phone:string;address:string;city:string;pin_code:string;status:string;shipping_fee:number;created_at:string};
const states=["all","pending","confirmed","processing","shipped","delivered","cancelled"];
export default function ShippingPage(){const[o,setO]=useState<Order[]>([]),[q,setQ]=useState(""),[filter,setFilter]=useState("all"),[selected,setSelected]=useState<Order|null>(null),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 async function load(){const s=getSupabaseBrowserClient();if(!s){setMessage("SUPABASE CONNECTION IS NOT CONFIGURED.");setLoading(false);return}setLoading(true);const{data,error}=await s.from("orders").select("id,customer_name,phone,address,city,pin_code,status,shipping_fee,created_at").order("created_at",{ascending:false});if(error)setMessage(error.message.toUpperCase());else setO((data||[])as Order[]);setLoading(false)}useEffect(()=>{load()},[]);
 const visible=useMemo(()=>{const x=q.trim().toLowerCase();return o.filter(v=>(filter==="all"||v.status===filter)&&(!x||v.customer_name.toLowerCase().includes(x)||v.phone.toLowerCase().includes(x)||v.city.toLowerCase().includes(x)||v.pin_code.toLowerCase().includes(x)||v.id.toLowerCase().includes(x)))},[o,q,filter]);const metrics=useMemo(()=>({ready:o.filter(x=>["confirmed","processing"].includes(x.status)).length,shipped:o.filter(x=>x.status==="shipped").length,delivered:o.filter(x=>x.status==="delivered").length,pending:o.filter(x=>x.status==="pending").length}),[o]);
 const money=(v:number)=>`₹ ${Number(v||0).toLocaleString("en-IN")}`;const update=async(status:string)=>{if(!selected)return;const s=getSupabaseBrowserClient();if(!s)return;const{data,error}=await s.from("orders").update({status,updated_at:new Date().toISOString()}).eq("id",selected.id).select("id,customer_name,phone,address,city,pin_code,status,shipping_fee,created_at").single();if(error)setMessage(error.message.toUpperCase());else{setO(x=>x.map(v=>v.id===selected.id?data as Order:v));setSelected(data as Order);setMessage("DELIVERY STATUS UPDATED ✓")}};
 return <div className="admin-page"><header className="admin-page-head"><div><span className="admin-eyebrow">10 — SHIPPING</span><h1>Delivery <i>Control.</i></h1><p>Prepare, dispatch and track every customer delivery.</p></div><button className="admin-action" onClick={load}>REFRESH ↻</button></header><section className="stat-grid"><div className="stat-card"><strong>{metrics.pending}</strong><span>Awaiting confirmation</span></div><div className="stat-card"><strong>{metrics.ready}</strong><span>Preparing</span></div><div className="stat-card"><strong>{metrics.shipped}</strong><span>In transit</span></div><div className="stat-card"><strong>{metrics.delivered}</strong><span>Delivered</span></div></section><div className="admin-toolbar"><input className="admin-search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search customer, phone, city, PIN or order ID…"/></div><div className="admin-tabs">{states.map(s=><button key={s} className={filter===s?"active":""} onClick={()=>setFilter(s)}>{s.toUpperCase()}</button>)}</div>{message&&<div className="admin-notice">{message}</div>}{loading?<div className="admin-empty">LOADING DELIVERY QUEUE…</div>:visible.length===0?<div className="admin-empty"><h2>Delivery queue is clear.</h2></div>:<div className="order-table"><div className="order-row order-head"><span>ORDER</span><span>CUSTOMER</span><span>DESTINATION</span><span>STATUS</span><span>SHIP FEE</span></div>{visible.map(x=><button className="order-row" key={x.id} onClick={()=>setSelected(x)}><span>#{x.id.slice(0,8).toUpperCase()}</span><span><strong>{x.customer_name}</strong><small>{x.phone}</small></span><span>{x.city}<small>{x.pin_code}</small></span><span><em className={`status status-${x.status}`}>{x.status}</em></span><span>{money(x.shipping_fee)}</span></button>)}</div>}{selected&&<div className="order-drawer-backdrop" onClick={()=>setSelected(null)}><aside className="order-drawer" onClick={e=>e.stopPropagation()}><button className="drawer-close" onClick={()=>setSelected(null)}>CLOSE ×</button><span className="admin-eyebrow">DELIVERY / {selected.id.slice(0,8).toUpperCase()}</span><h2>{selected.customer_name}</h2><div className="drawer-meta"><p>{selected.phone}</p><p>{selected.address}</p><p>{selected.city} — {selected.pin_code}</p></div><div className="drawer-status"><label>DELIVERY STATUS<select value={selected.status} onChange={e=>update(e.target.value)}>{states.filter(s=>s!=="all").map(s=><option key={s} value={s}>{s.toUpperCase()}</option>)}</select></label></div><p className="drawer-note">Current flow: pending → confirmed → processing → shipped → delivered. Use the Orders desk for payment and full order details.</p></aside></div>}</div>}
