"use client";

import { useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase-browser";

type CmsRow = { id: string; section: string; eyebrow: string | null; title: string | null; body: string | null; link_label: string | null; link_url: string | null; content_json: Record<string, unknown>; is_active: boolean };
type Product = { id: string; name: string; slug: string; price: number };
type Category = { id: string; name: string; slug: string };
const sectionLabels: Record<string, string> = { hero: "Homepage Hero", story: "Story Section", featured_products: "Featured Products", featured_collections: "Featured Collections", banner: "Banner Management", footer: "Footer Content" };

export default function CmsPage() {
  const [rows, setRows] = useState<CmsRow[]>([]); const [products, setProducts] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]);
  const [selected, setSelected] = useState("hero"); const [form, setForm] = useState<CmsRow | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const selectedRow = useMemo(() => rows.find(row => row.section === selected) ?? null, [rows, selected]);
  useEffect(() => { (async () => { const supabase = getSupabaseBrowserClient(); if (!supabase) { setMessage("Supabase is not configured."); setLoading(false); return; } const [{ data: cms, error }, { data: p }, { data: c }] = await Promise.all([supabase.from("storefront_content").select("id,section,eyebrow,title,body,link_label,link_url,content_json,is_active").order("section"), supabase.from("products").select("id,name,slug,price").eq("is_active", true).order("created_at", { ascending: false }), supabase.from("categories").select("id,name,slug").eq("is_active", true).order("display_order", { ascending: true })]); if (error) setMessage(error.message); else setRows((cms ?? []) as CmsRow[]); setProducts((p ?? []) as Product[]); setCategories((c ?? []) as Category[]); setLoading(false); })(); }, []);
  useEffect(() => { if (selectedRow) setForm(JSON.parse(JSON.stringify(selectedRow))); }, [selectedRow]);
  const patch = (key: keyof CmsRow, value: unknown) => setForm(current => current ? { ...current, [key]: value } : current);
  const toggleId = (key: "product_ids" | "category_ids", id: string) => setForm(current => { if (!current) return current; const old = Array.isArray(current.content_json?.[key]) ? current.content_json[key] as string[] : []; return { ...current, content_json: { ...current.content_json, [key]: old.includes(id) ? old.filter(x => x !== id) : [...old, id] } }; });
  const save = async () => { if (!form) return; const supabase = getSupabaseBrowserClient(); if (!supabase) return; setSaving(true); setMessage(""); const { data, error } = await supabase.from("storefront_content").update({ eyebrow: form.eyebrow, title: form.title, body: form.body, link_label: form.link_label, link_url: form.link_url, content_json: form.content_json, is_active: form.is_active, updated_at: new Date().toISOString() }).eq("id", form.id).select("id,section,eyebrow,title,body,link_label,link_url,content_json,is_active").single(); if (error) setMessage(error.message); else { setRows(current => current.map(row => row.id === form.id ? data as CmsRow : row)); setMessage("PUBLISHED ✓"); } setSaving(false); window.setTimeout(() => setMessage(""), 1800); };
  const createSection = async (section: string) => { const supabase = getSupabaseBrowserClient(); if (!supabase) return; const { data, error } = await supabase.from("storefront_content").insert({ section, title: sectionLabels[section], content_json: {}, is_active: false }).select("id,section,eyebrow,title,body,link_label,link_url,content_json,is_active").single(); if (error) setMessage(error.message); else { setRows(current => [...current, data as CmsRow]); setSelected(section); } };
  return <div className="admin-page"><header className="admin-page-head"><div><span className="admin-eyebrow">06 — WEBSITE / CMS</span><h1>Shape the <i>store.</i></h1><p>Live storefront content, publishing controls and featured merchandising.</p></div><button className="admin-action" onClick={save} disabled={saving || !form}>{saving ? "SAVING…" : message || "PUBLISH CHANGES"}</button></header>
    {loading ? <div className="admin-empty">LOADING CMS…</div> : <><section className="cms-editor"><div className="admin-section-title"><span>LIVE SECTIONS</span><span>EDIT / PUBLISH</span></div>{Object.keys(sectionLabels).map((key, index) => { const row = rows.find(x => x.section === key); return <article className={`cms-row ${selected === key ? "cms-row-active" : ""}`} key={key}><span>{String(index + 1).padStart(2, "0")}</span><div><small>{sectionLabels[key]}</small><strong>{row?.title || "Not created yet"}</strong></div><button type="button" onClick={() => row ? setSelected(key) : createSection(key)}>{row ? (row.is_active ? "LIVE ↗" : "EDIT ↗") : "CREATE +"}</button></article>; })}</section>
    {form && <section className="cms-form"><div className="admin-section-title"><span>EDIT — {sectionLabels[form.section]}</span><label><input type="checkbox" checked={form.is_active} onChange={e => patch("is_active", e.target.checked)} /> ACTIVE / PUBLISHED</label></div><div className="cms-fields"><label>Eyebrow<input value={form.eyebrow ?? ""} onChange={e => patch("eyebrow", e.target.value)} /></label><label>Title<textarea rows={2} value={form.title ?? ""} onChange={e => patch("title", e.target.value)} /></label><label>Body<textarea rows={4} value={form.body ?? ""} onChange={e => patch("body", e.target.value)} /></label><label>Link label<input value={form.link_label ?? ""} onChange={e => patch("link_label", e.target.value)} /></label><label>Link URL<input value={form.link_url ?? ""} onChange={e => patch("link_url", e.target.value)} /></label>{form.section === "banner" && <label>Banner image URL<input value={String(form.content_json?.image_url ?? "")} onChange={e => patch("content_json", { ...form.content_json, image_url: e.target.value })} placeholder="https://…" /></label>}
    {form.section === "featured_products" && <div className="cms-picker"><small>FEATURED PRODUCTS</small>{products.map(product => { const ids = Array.isArray(form.content_json?.product_ids) ? form.content_json.product_ids as string[] : []; return <label key={product.id}><input type="checkbox" checked={ids.includes(product.id)} onChange={() => toggleId("product_ids", product.id)} /> {product.name} — ₹ {Number(product.price).toLocaleString("en-IN")}</label>; })}</div>}
    {form.section === "featured_collections" && <div className="cms-picker"><small>FEATURED COLLECTIONS</small>{categories.map(category => { const ids = Array.isArray(form.content_json?.category_ids) ? form.content_json.category_ids as string[] : []; return <label key={category.id}><input type="checkbox" checked={ids.includes(category.id)} onChange={() => toggleId("category_ids", category.id)} /> {category.name}</label>; })}</div>}</div></section>}</>}</div>;
}
