"use client";

import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase-browser";
import { uploadProductImage } from "@/lib/product-image-upload";

type Product={id:string;name:string;slug:string;description:string|null;price:number;compare_at_price:number|null;sku:string|null;stock:number;sizes:string[];image_url:string|null;is_active:boolean;category_id:string|null;seo_title:string|null;seo_description:string|null;material:string|null;care_instructions:string|null;featured:boolean};
type Category={id:string;name:string};
type GalleryImage={id:string;product_id:string;image_url:string;alt_text:string|null;display_order:number;is_primary:boolean};
type ImageSlot={id:string;url:string;file:File|null;preview:string};
const blank={name:"",slug:"",description:"",price:"",compare:"",sku:"",stock:"0",sizes:"",category:"",active:true,seoTitle:"",seoDescription:"",material:"",care:"",featured:false};
const MAX_IMAGES=5;
const emptySlot=():ImageSlot=>({id:crypto.randomUUID(),url:"",file:null,preview:""});

export default function ProductsAdminPage(){
 const [products,setProducts]=useState<Product[]>([]),[categories,setCategories]=useState<Category[]>([]),[form,setForm]=useState(blank),[editing,setEditing]=useState<string|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 const [images,setImages]=useState<ImageSlot[]>([emptySlot()]);
 const supabase=getSupabaseBrowserClient();
 async function load(){setLoading(true);if(!supabase){setMessage("SUPABASE ENVIRONMENT VARIABLES ARE NOT CONFIGURED.");setLoading(false);return;}const [{data:p,error:pe},{data:c}]=await Promise.all([supabase.from("products").select("id,name,slug,description,price,compare_at_price,sku,stock,sizes,image_url,is_active,category_id,seo_title,seo_description,material,care_instructions,featured").order("created_at",{ascending:false}),supabase.from("categories").select("id,name").order("display_order",{ascending:true})]);if(pe)setMessage(pe.message.toUpperCase());else setProducts((p as Product[])||[]);setCategories((c as Category[])||[]);setLoading(false);}
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(!editing||!supabase)return;(async()=>{const {data,error}=await supabase.from("product_images").select("id,product_id,image_url,alt_text,display_order,is_primary").eq("product_id",editing).order("display_order",{ascending:true});if(error){setMessage(error.message.toUpperCase());return;}const rows=(data||[]) as GalleryImage[];setImages(rows.length?rows.slice(0,MAX_IMAGES).map(x=>({id:x.id,url:x.image_url,file:null,preview:x.image_url})):[emptySlot()]);})();},[editing]);
 function change(key:keyof typeof blank,value:string|boolean){setForm(f=>({...f,[key]:value}));}
 function slugify(v:string){return v.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");}
 function edit(p:Product){setEditing(p.id);setForm({name:p.name,slug:p.slug,description:p.description||"",price:String(p.price),compare:p.compare_at_price==null?"":String(p.compare_at_price),sku:p.sku||"",stock:String(p.stock),sizes:(p.sizes||[]).join(", "),category:p.category_id||"",active:p.is_active,seoTitle:p.seo_title||"",seoDescription:p.seo_description||"",material:p.material||"",care:p.care_instructions||"",featured:p.featured});window.scrollTo({top:0,behavior:"smooth"});}
 function reset(){setEditing(null);setForm(blank);setImages([emptySlot()]);setMessage("");}
 function addSlot(){if(images.length<MAX_IMAGES)setImages(v=>[...v,emptySlot()]);}
 function removeSlot(index:number){setImages(v=>{const n=v.filter((_,i)=>i!==index);return n.length?n:[emptySlot()]});}
 function setUrl(index:number,value:string){setImages(v=>v.map((x,i)=>i===index?{...x,url:value,preview:value,file:null}:x));}
 function handleFile(index:number,e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value="";if(!file)return;if(file.size>5*1024*1024){setMessage("MAXIMUM IMAGE FILE SIZE IS 5MB.");return;}if(!/^image\/(jpeg|png|webp)$/.test(file.type)){setMessage("ONLY JPG, PNG OR WEBP IMAGES ARE ALLOWED.");return;}const preview=URL.createObjectURL(file);setImages(v=>v.map((x,i)=>i===index?{...x,file,url:"",preview}:x));setMessage("");}
 async function syncImages(productId:string,slug:string,name:string){if(!supabase)return;for(let i=0;i<images.length;i++){const slot=images[i];if(!slot.file&&!slot.url.trim())continue;let imageUrl=slot.url.trim();if(slot.file)imageUrl=await uploadProductImage(supabase,slot.file,slug);try{new URL(imageUrl)}catch{throw new Error(`INVALID IMAGE URL IN IMAGE ${i+1}.`)}const {data:existing}=await supabase.from("product_images").select("id").eq("product_id",productId).eq("image_url",imageUrl).maybeSingle();if(existing?.id)continue;const {error}=await supabase.from("product_images").insert({product_id:productId,image_url:imageUrl,alt_text:name,display_order:i,is_primary:i===0});if(error)throw error;if(i===0)await supabase.from("products").update({image_url:imageUrl,updated_at:new Date().toISOString()}).eq("id",productId);}}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setMessage("");if(!supabase){setMessage("SUPABASE ENVIRONMENT VARIABLES ARE NOT CONFIGURED.");setSaving(false);return;}const name=form.name.trim(),slug=form.slug.trim()||slugify(name),price=Number(form.price),compare=form.compare.trim()?Number(form.compare):null,stock=Number(form.stock);if(!name||!slug){setMessage("PRODUCT NAME IS REQUIRED.");setSaving(false);return;}if(!Number.isFinite(price)||price<0){setMessage("PRICE MUST BE A VALID NON-NEGATIVE NUMBER.");setSaving(false);return;}if(compare!==null&&(!Number.isFinite(compare)||compare<price)){setMessage("COMPARE PRICE MUST BE VALID AND NOT LOWER THAN PRICE.");setSaving(false);return;}if(!Number.isFinite(stock)||stock<0){setMessage("STOCK MUST BE A VALID NON-NEGATIVE NUMBER.");setSaving(false);return;}const payload={name,slug,description:form.description.trim()||null,price,compare_at_price:compare,sku:form.sku.trim()||null,stock:Math.floor(stock),sizes:form.sizes.split(",").map(x=>x.trim()).filter(Boolean),category_id:form.category||null,is_active:Boolean(form.active),seo_title:form.seoTitle.trim()||null,seo_description:form.seoDescription.trim()||null,material:form.material.trim()||null,care_instructions:form.care.trim()||null,featured:Boolean(form.featured),updated_at:new Date().toISOString()};try{let productId=editing;if(editing){const {error}=await supabase.from("products").update(payload).eq("id",editing);if(error)throw error;}else{const {data,error}=await supabase.from("products").insert(payload).select("id").single();if(error)throw error;productId=data.id;setEditing(productId);}await syncImages(productId!,slug,name);setMessage(editing?"PRODUCT UPDATED + PHOTOS SAVED.":"PRODUCT CREATED + PHOTOS SAVED.");await load();const {data:rows}=await supabase.from("product_images").select("id,product_id,image_url,alt_text,display_order,is_primary").eq("product_id",productId).order("display_order",{ascending:true});setImages(rows?.length?(rows as GalleryImage[]).slice(0,MAX_IMAGES).map(x=>({id:x.id,url:x.image_url,file:null,preview:x.image_url})):[emptySlot()]);}catch(err){setMessage(err instanceof Error?err.message.toUpperCase():"PRODUCT SAVE FAILED.");}finally{setSaving(false);}}
 async function toggle(p:Product){if(!supabase)return;const{error}=await supabase.from("products").update({is_active:!p.is_active,updated_at:new Date().toISOString()}).eq("id",p.id);if(error)setMessage(error.message.toUpperCase());else load();}
 async function remove(p:Product){if(!window.confirm(`Delete ${p.name}?`))return;if(!supabase)return;const{error}=await supabase.from("products").delete().eq("id",p.id);if(error)setMessage(error.message.toUpperCase());else{if(editing===p.id)reset();load();}}
 return <div className="admin-dashboard"><header className="admin-header"><div><span>02 — CATALOG</span><h1>PRODUCT<br/><i>ROOM.</i></h1></div><div className="admin-status"><span className="status-dot"/> SUPABASE / LIVE<br/><small>PRODUCT CRUD + GALLERY + METADATA</small></div></header><section className="admin-section"><div className="admin-section-title"><span>{editing?"EDIT PRODUCT":"ADD PRODUCT"}</span><span>CATALOG / CORE</span></div><form className="admin-form" onSubmit={save}><label>Product name<input required value={form.name} onChange={e=>change("name",e.target.value)} placeholder="Gulab Silk Saree"/></label><label>Slug<input value={form.slug} onChange={e=>change("slug",e.target.value)} placeholder="gulab-silk-saree"/></label><label>Category<select value={form.category} onChange={e=>change("category",e.target.value)}><option value="">Select category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Description<textarea value={form.description} onChange={e=>change("description",e.target.value)} rows={3}/></label><div className="form-row"><label>Price<input required type="number" min="0" step="0.01" value={form.price} onChange={e=>change("price",e.target.value)}/></label><label>Compare price<input type="number" min="0" step="0.01" value={form.compare} onChange={e=>change("compare",e.target.value)}/></label></div><div className="form-row"><label>SKU<input value={form.sku} onChange={e=>change("sku",e.target.value)}/></label><label>Stock<input type="number" min="0" step="1" value={form.stock} onChange={e=>change("stock",e.target.value)}/></label></div><label>Sizes <small>comma separated</small><input value={form.sizes} onChange={e=>change("sizes",e.target.value)} placeholder="Free Size, 36, 38"/></label><label>Material<input value={form.material} onChange={e=>change("material",e.target.value)} placeholder="Pure cotton / silk blend"/></label><label>Care instructions<textarea value={form.care} onChange={e=>change("care",e.target.value)} rows={3} placeholder="Dry clean recommended"/></label><label>SEO title<input value={form.seoTitle} onChange={e=>change("seoTitle",e.target.value)} maxLength={70}/></label><label>SEO description<textarea value={form.seoDescription} onChange={e=>change("seoDescription",e.target.value)} rows={3} maxLength={160}/></label>
 <div className="admin-gallery-section admin-form-gallery"><div className="admin-section-title"><div><span>PRODUCT PHOTOS / {images.length} OF {MAX_IMAGES}</span><small className="admin-gallery-hint">LOCAL UPLOAD OR IMAGE URL · IMAGE 1 = PRIMARY · IMAGE 2 = HOVER · IMAGES 3–5 = PDP GALLERY</small></div></div><div className="admin-form-gallery-list">{images.map((slot,index)=><div className="admin-form-gallery-row" key={slot.id}><div className="admin-form-gallery-preview">{slot.preview?<img src={slot.preview} alt={`Image ${index+1}`}/>:<span>IMAGE {index+1}</span>}</div><div className="admin-form-gallery-fields"><strong>IMAGE {index+1} · {index===0?"PRIMARY":index===1?"HOVER":"PDP GALLERY"}</strong><div className="admin-gallery-row-input"><input type="url" value={slot.url} onChange={e=>setUrl(index,e.target.value)} placeholder="Paste image URL…" disabled={saving}/><label className="admin-action admin-upload-button">UPLOAD<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>handleFile(index,e)} disabled={saving}/></label>{images.length>1&&<button type="button" className="table-action danger" onClick={()=>removeSlot(index)} disabled={saving}>REMOVE</button>}</div>{slot.file&&<small>{slot.file.name}</small>}</div></div>)}</div>{images.length<MAX_IMAGES&&<button type="button" className="admin-action admin-add-image" onClick={addSlot} disabled={saving}>+ ADD ANOTHER IMAGE</button>}</div>
 <label className="check-row"><input type="checkbox" checked={form.featured} onChange={e=>change("featured",e.target.checked)}/> Featured product</label><label className="check-row"><input type="checkbox" checked={form.active} onChange={e=>change("active",e.target.checked)}/> Active on storefront</label><div className="form-actions"><button className="admin-action admin-submit" disabled={saving}>{saving?"SAVING…":editing?"UPDATE PRODUCT →":"CREATE PRODUCT →"}</button>{editing&&<button type="button" className="admin-action" onClick={reset}>NEW PRODUCT</button>}</div></form>{message&&<div className="admin-empty">{message}</div>}</section><section className="admin-section"><div className="admin-section-title"><span>PRODUCTS / {products.length}</span><button className="admin-action" onClick={load}>REFRESH ↻</button></div>{loading?<div className="admin-empty">LOADING PRODUCTS…</div>:products.length===0?<div className="admin-empty">NO PRODUCTS YET.</div>:<div className="admin-table"><div className="admin-row admin-row-head"><span>PRODUCT</span><span>SKU</span><span>PRICE</span><span>STOCK</span><span>ACTION</span></div>{products.map(p=><div className="admin-row" key={p.id}><strong>{p.name}</strong><span>{p.sku||"—"}</span><span>₹ {Number(p.price).toLocaleString("en-IN")}</span><span>{p.stock}</span><span className="row-actions"><button className="table-action" onClick={()=>edit(p)}>EDIT</button><button className="table-action" onClick={()=>toggle(p)}>{p.is_active?"HIDE":"SHOW"}</button><button className="table-action danger" onClick={()=>remove(p)}>DELETE</button></span></div>)}</div>}</section></div>;
}
