"use client";

import { useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase-browser";
import MotionEnhancer from "./motion-enhancer";
import ProductCard from "./product-card";
import Link from "next/link";

type Product = { id: string; slug: string; name: string; price: number; image_url: string | null; category_id: string | null };
type Category = { id: string; name: string; slug: string };
type CmsRow = { section: string; eyebrow: string | null; title: string | null; body: string | null; link_label: string | null; link_url: string | null; is_active: boolean; content_json: Record<string, unknown> | null };
const fallbackProducts: Product[] = [{ id:"01",slug:"gulab",name:"Gulab Silk Saree",price:2499,image_url:null,category_id:null },{ id:"02",slug:"noor",name:"Noor Handloom Saree",price:2899,image_url:null,category_id:null },{ id:"03",slug:"madhubani",name:"Madhubani Saree",price:3199,image_url:null,category_id:null },{ id:"04",slug:"meher",name:"Meher Cotton Saree",price:2199,image_url:null,category_id:null }];
const fallbackCms: Record<string,CmsRow> = { hero:{section:"hero",eyebrow:"LE SHE SAREE / HANDCRAFTED INDIA",title:"TRADITION IN MOTION.",body:"Sarees made with Indian craft, softened by time, and designed for the way you live now.",link_label:"Explore collection",link_url:"#shop",is_active:true,content_json:{}},story:{section:"story",eyebrow:"CRAFTED IN INDIA",title:"WORN YOUR WAY.",body:"LE SHE SAREE brings the quiet richness of Indian textiles into an expressive, modern wardrobe.",link_label:null,link_url:null,is_active:true,content_json:{}},featured_products:{section:"featured_products",eyebrow:"01 — COLLECTION",title:"NEW ARRIVALS",body:null,link_label:null,link_url:null,is_active:true,content_json:{}},featured_collections:{section:"featured_collections",eyebrow:null,title:"EXPLORE COLLECTIONS",body:null,link_label:null,link_url:null,is_active:true,content_json:{}},banner:{section:"banner",eyebrow:"HANDCRAFTED INDIA",title:"",body:null,link_label:null,link_url:null,is_active:false,content_json:{}},footer:{section:"footer",eyebrow:null,title:"LE SHE SAREE",body:"Made to be worn. Made to be remembered.",link_label:"Shipping & Returns",link_url:"/shipping-and-return",is_active:true,content_json:{}} };

function cmsImage(row: CmsRow | undefined) {
  const json = row?.content_json;
  if (!json) return null;
  const candidates = [json.hero_image_url, json.image_url, json.image, json.desktop_image, json.cover_image];
  return candidates.find((value): value is string => typeof value === "string" && value.trim().length > 0)?.trim() || null;
}

export default function Home(){
 const [intro,setIntro]=useState(true),[pointer,setPointer]=useState({x:0,y:0}),[bagCount,setBagCount]=useState(0),[products,setProducts]=useState<Product[]>(fallbackProducts),[categories,setCategories]=useState<Category[]>([]),[cms,setCms]=useState<Record<string,CmsRow>>(fallbackCms),[activeCategory,setActiveCategory]=useState("all"),[query,setQuery]=useState(""),[searchOpen,setSearchOpen]=useState(false),[loading,setLoading]=useState(true);
 useEffect(()=>{const timer=window.setTimeout(()=>setIntro(false),1600);const onMove=(e:MouseEvent)=>setPointer({x:e.clientX,y:e.clientY});const readBag=()=>setBagCount(Number(window.localStorage.getItem("leshe-bag-count")||0));const load=async()=>{const s=getSupabaseBrowserClient();if(!s){setLoading(false);return}try{const [{data:p},{data:c},{data:m}]=await Promise.all([s.from("products").select("id,slug,name,price,image_url,category_id").eq("is_active",true).order("created_at",{ascending:false}),s.from("categories").select("id,name,slug").eq("is_active",true).order("display_order",{ascending:true}),s.from("storefront_content").select("section,eyebrow,title,body,link_label,link_url,is_active,content_json").eq("is_active",true)]);if(p?.length)setProducts(p as Product[]);if(c?.length)setCategories(c as Category[]);if(m?.length)setCms(cur=>({...cur,...Object.fromEntries((m as CmsRow[]).map(r=>[r.section,r]))}));}finally{setLoading(false)}};window.addEventListener("mousemove",onMove);window.addEventListener("storage",readBag);window.addEventListener("leshe-bag-updated",readBag);readBag();load();return()=>{window.clearTimeout(timer);window.removeEventListener("mousemove",onMove);window.removeEventListener("storage",readBag);window.removeEventListener("leshe-bag-updated",readBag)}},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==="/"&&!e.metaKey&&!e.ctrlKey&&document.activeElement?.tagName!=="INPUT"){e.preventDefault();setSearchOpen(true);window.setTimeout(()=>document.getElementById("storefront-search")?.focus(),0)}if(e.key==="Escape")setSearchOpen(false)};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[]);
 const visibleProducts=useMemo(()=>{const base=activeCategory==="all"?products:products.filter(p=>p.category_id===activeCategory);const q=query.trim().toLowerCase();return q?base.filter(p=>`${p.name} ${p.slug}`.toLowerCase().includes(q)):base},[activeCategory,products,query]);
 const hero=cms.hero,story=cms.story,featured=cms.featured_products,footer=cms.footer;const heroImage=cmsImage(hero);const featuredIds=Array.isArray(featured.content_json?.product_ids)?featured.content_json.product_ids as string[]:[];const catalogProducts=featuredIds.length?visibleProducts.filter(p=>featuredIds.includes(p.id)):visibleProducts;
 return <main id="top" className="site-shell" style={{"--mx":`${pointer.x}px`,"--my":`${pointer.y}px`} as React.CSSProperties}><MotionEnhancer/><div className={`cursor ${intro?"cursor-hidden":""}`} aria-hidden="true"><span>VIEW</span></div><div className={`intro ${intro?"intro-visible":"intro-hidden"}`} aria-hidden={!intro}><div className="intro-mark">LE SHE</div><div className="intro-count">100</div></div>
 <header className="topbar"><a className="brand wordmark" href="#top" aria-label="LE SHE SAREE home">LE SHE<br/><span>SAREE</span></a><nav aria-label="Main navigation"><a href="#shop">Shop</a><a href="#story">Story</a><Link href="/wishlist">Wishlist</Link><a href="/bag" aria-label={`Shopping bag, ${bagCount} items`}>Bag ({bagCount})</a></nav><button type="button" className="search-trigger" onClick={()=>setSearchOpen(true)} aria-expanded={searchOpen}>SEARCH /</button></header>
 {searchOpen&&<div className="search-panel" role="search"><div className="search-panel-inner"><span>FIND A PIECE</span><input id="storefront-search" autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search sarees, collections…"/><button type="button" onClick={()=>{setQuery("");setSearchOpen(false)}} aria-label="Close search">×</button><small>Press / to search · ESC to close</small></div></div>}
 <section className={`hero ${heroImage?"hero-with-image":""}`} aria-labelledby="hero-title">{heroImage&&<div className="hero-visual" aria-hidden="true"><img src={heroImage} alt="" loading="eager" fetchPriority="high"/></div>}<div className="hero-content"><p className="eyebrow">{hero.eyebrow}</p><h1 id="hero-title">{(hero.title||"TRADITION IN MOTION.").split(" ").map((word,i,words)=><span key={`${word}-${i}`}>{word}{i<words.length-1?" ":""}</span>)}</h1><p className="hero-copy">{hero.body}</p><a className="hero-link magnetic" href={hero.link_url||"#shop"}>{hero.link_label||"Explore collection"} <b aria-hidden="true">↓</b></a></div></section>
 <section id="shop" className="collection" aria-labelledby="collection-title"><div className="section-head"><span>{featured.eyebrow||"01 — COLLECTION"}</span><span id="collection-title">{featured.title||"NEW ARRIVALS"} / {catalogProducts.length}</span></div><div className="category-nav" role="tablist" aria-label="Filter products by category"><button type="button" role="tab" aria-selected={activeCategory==="all"} className={activeCategory==="all"?"selected":""} onClick={()=>setActiveCategory("all")}>ALL</button>{categories.map(c=><button type="button" role="tab" aria-selected={activeCategory===c.id} className={activeCategory===c.id?"selected":""} onClick={()=>setActiveCategory(c.id)} key={c.id}>{c.name}</button>)}</div>{query&&<div className="search-results-note">SEARCH / <strong>{query}</strong> / {catalogProducts.length}</div>}{loading?<div className="product-grid product-grid-loading" aria-label="Loading products">{[1,2,3,4].map(i=><div className="product-skeleton" key={i}><div/><span/><span/></div>)}</div>:<div className="product-grid">{catalogProducts.map((p,i)=><ProductCard key={p.id} product={p} index={i} categoryName={categories.find(c=>c.id===p.category_id)?.name}/>)}</div>}{!loading&&!catalogProducts.length&&<div className="storefront-empty"><strong>NOTHING HERE YET.</strong><span>Try another search or collection.</span><button type="button" onClick={()=>{setQuery("");setActiveCategory("all")}}>VIEW ALL →</button></div>}</section>
 <section id="story" className="statement" aria-labelledby="story-title"><span>{story.eyebrow}</span><strong id="story-title">{(story.title||"WORN YOUR WAY.").split(" ").map((w,i)=><span key={`${w}-${i}`}>{w}<br/></span>)}</strong><p>{story.body}</p></section><footer><div className="footer-big">{footer.title||"LE SHE SAREE"}</div><div className="footer-bottom"><span>© 2026 LE SHE SAREE</span><span>{footer.body||"Made to be worn. Made to be remembered."}</span><a href={footer.link_url||"/shipping-and-return"}>{footer.link_label||"Shipping & Returns"}</a></div></footer></main>;
}
