"use client";
import { useEffect, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase-browser";
import styles from "./product-card-reference.module.css";
type ProductImage={image_url:string;display_order:number;is_primary:boolean};
type Product={id:string;slug:string;name:string;price:number;image_url:string|null};
type Wish=Product;
type CartItem={product_id:string;slug:string;name:string;price:number;image_url:string|null;quantity:number;size:string};
const displayImageUrl=(url:string|null)=>{if(!url)return null;try{const parsed=new URL(url);if(parsed.protocol==="https:"&&(parsed.hostname==="i.ibb.co"||parsed.hostname==="ibb.co"))return `/api/image-proxy?url=${encodeURIComponent(url)}`;}catch{}return url;};
function writeBag(item:CartItem,replace=false){let items:CartItem[]=[];try{items=JSON.parse(localStorage.getItem("leshe-bag-items")||"[]")}catch{};if(replace)items=[item];else{const index=items.findIndex(x=>x.product_id===item.product_id&&x.size===item.size);if(index>=0)items[index].quantity+=1;else items.push(item);}const count=items.reduce((sum,x)=>sum+x.quantity,0);localStorage.setItem("leshe-bag-items",JSON.stringify(items));localStorage.setItem("leshe-bag-count",String(count));window.dispatchEvent(new Event("leshe-bag-updated"));}
export default function ProductCard({product,index,categoryName}:{product:Product;index:number;categoryName?:string}){
 const [images,setImages]=useState<string[]>([]);const [saved,setSaved]=useState(false);const [imageFailed,setImageFailed]=useState(false);const [added,setAdded]=useState(false);
 useEffect(()=>{let active=true;setImageFailed(false);const load=async()=>{const s=getSupabaseBrowserClient();if(s){const {data}=await s.from("product_images").select("image_url,display_order,is_primary").eq("product_id",product.id).order("is_primary",{ascending:false}).order("display_order",{ascending:true});if(active){const gallery=((data||[])as ProductImage[]).map(x=>x.image_url).filter(Boolean);setImages(Array.from(new Set([...(product.image_url?[product.image_url]:[]),...gallery])));}}try{const list=JSON.parse(localStorage.getItem("leshe-wishlist")||"[]")as Wish[];setSaved(list.some(x=>x.id===product.id||x.slug===product.slug));}catch{}};load();const sync=()=>{try{const list=JSON.parse(localStorage.getItem("leshe-wishlist")||"[]")as Wish[];setSaved(list.some(x=>x.id===product.id||x.slug===product.slug));}catch{}};window.addEventListener("leshe-wishlist-updated",sync);return()=>{active=false;window.removeEventListener("leshe-wishlist-updated",sync)}} , [product.id,product.image_url,product.slug]);
 const toggle=(e:React.MouseEvent)=>{e.preventDefault();e.stopPropagation();let list:Wish[]=[];try{list=JSON.parse(localStorage.getItem("leshe-wishlist")||"[]")}catch{};const exists=list.some(x=>x.id===product.id||x.slug===product.slug);const next=exists?list.filter(x=>x.id!==product.id&&x.slug!==product.slug):[...list,product];localStorage.setItem("leshe-wishlist",JSON.stringify(next));setSaved(!exists);window.dispatchEvent(new Event("leshe-wishlist-updated"));};
 const addToCart=(e:React.MouseEvent)=>{e.preventDefault();e.stopPropagation();writeBag({product_id:product.id,slug:product.slug,name:product.name,price:Number(product.price),image_url:displayImageUrl(product.image_url),quantity:1,size:"Free Size"});setAdded(true);window.setTimeout(()=>setAdded(false),1000)};
 const buyNow=(e:React.MouseEvent)=>{e.preventDefault();e.stopPropagation();writeBag({product_id:product.id,slug:product.slug,name:product.name,price:Number(product.price),image_url:displayImageUrl(product.image_url),quantity:1,size:"Free Size"},true);window.location.href="/checkout";};
 const primary=images[0]||product.image_url,hover=images[1]||primary,tone=["rose","stone","plum","sand"][index%4];
 const primarySrc=displayImageUrl(primary),hoverSrc=displayImageUrl(hover);
 return <article className={styles.card}><a href={`/product/${product.slug}`} aria-label={`View ${product.name}`}><div className={`${styles.image} tone-${tone}`}>{primarySrc&&!imageFailed?<><img className={`${styles.photo} ${styles.primary}`} src={primarySrc} alt={product.name} onError={()=>setImageFailed(true)}/>{hoverSrc&&<img className={`${styles.photo} ${styles.hover}`} src={hoverSrc} alt="" aria-hidden="true" onError={(e)=>{e.currentTarget.style.display="none"}}/>}</>:<span className={styles.fallback}>{product.name.split(" ")[0].toUpperCase()}</span>}<i>VIEW MORE</i></div><div className={styles.meta}><span>{product.name}</span><span>₹ {Number(product.price).toLocaleString("en-IN")}</span></div><div className={styles.category}>{categoryName||"COLLECTION"}</div></a><button type="button" className={styles.wishlist} onClick={toggle} aria-label={saved?`Remove ${product.name} from wishlist`:`Save ${product.name} to wishlist`} aria-pressed={saved}>{saved?"♥":"♡"}</button><div className={styles.actions}><button type="button" onClick={addToCart}>{added?"ADDED ✓":"ADD TO CART"}</button><button type="button" onClick={buyNow}>BUY NOW <span>→</span></button></div></article>;
}
