"use client";
import { useEffect, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase-browser";
import styles from "./product-card-reference.module.css";
type ProductImage={image_url:string;display_order:number;is_primary:boolean};
type Product={id:string;slug:string;name:string;price:number;image_url:string|null};
type Wish=Product;
export default function ProductCard({product,index,categoryName}:{product:Product;index:number;categoryName?:string}){
 const [images,setImages]=useState<string[]>([]);const [saved,setSaved]=useState(false);
 useEffect(()=>{let active=true;const load=async()=>{const s=getSupabaseBrowserClient();if(s){const {data}=await s.from("product_images").select("image_url,display_order,is_primary").eq("product_id",product.id).order("is_primary",{ascending:false}).order("display_order",{ascending:true});if(active){const gallery=((data||[])as ProductImage[]).map(x=>x.image_url).filter(Boolean);setImages(Array.from(new Set([...(product.image_url?[product.image_url]:[]),...gallery])));}}try{const list=JSON.parse(localStorage.getItem("leshe-wishlist")||"[]")as Wish[];setSaved(list.some(x=>x.id===product.id||x.slug===product.slug));}catch{}};load();const sync=()=>{try{const list=JSON.parse(localStorage.getItem("leshe-wishlist")||"[]")as Wish[];setSaved(list.some(x=>x.id===product.id||x.slug===product.slug));}catch{}};window.addEventListener("leshe-wishlist-updated",sync);return()=>{active=false;window.removeEventListener("leshe-wishlist-updated",sync)}} , [product.id,product.image_url,product.slug]);
 const toggle=(e:React.MouseEvent)=>{e.preventDefault();e.stopPropagation();let list:Wish[]=[];try{list=JSON.parse(localStorage.getItem("leshe-wishlist")||"[]")}catch{};const exists=list.some(x=>x.id===product.id||x.slug===product.slug);const next=exists?list.filter(x=>x.id!==product.id&&x.slug!==product.slug):[...list,product];localStorage.setItem("leshe-wishlist",JSON.stringify(next));setSaved(!exists);window.dispatchEvent(new Event("leshe-wishlist-updated"));};
 const primary=images[0]||product.image_url,hover=images[1]||primary,tone=["rose","stone","plum","sand"][index%4];
 return <article className={styles.card}><a href={`/product/${product.slug}`} aria-label={`View ${product.name}`}><div className={`${styles.image} tone-${tone}`}>{primary?<><img className={`${styles.photo} ${styles.primary}`} src={primary} alt={product.name}/><img className={`${styles.photo} ${styles.hover}`} src={hover||primary} alt="" aria-hidden="true"/></>:<span className={styles.fallback}>{product.name.split(" ")[0].toUpperCase()}</span>}<i>VIEW MORE</i></div><div className={styles.meta}><span>{product.name}</span><span>₹ {Number(product.price).toLocaleString("en-IN")}</span></div><div className={styles.category}>{categoryName||"COLLECTION"}</div></a><button type="button" className={styles.wishlist} onClick={toggle} aria-label={saved?`Remove ${product.name} from wishlist`:`Save ${product.name} to wishlist`} aria-pressed={saved}>{saved?"♥":"♡"}</button></article>;
}
