"use client";
import { useEffect, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase-browser";
const resources = ["products","categories","inventory","orders","customers","marketing","cms","settings"];
export default function AdminUsersPage() {
 const supabase=getSupabaseBrowserClient();
 const [rows,setRows]=useState<any[]>([]); const [perms,setPerms]=useState<any[]>([]); const [error,setError]=useState("");
 useEffect(()=>{(async()=>{if(!supabase)return; const a=await supabase.from("profiles").select("id,full_name,role,is_active,created_at").in("role",["admin","master_admin"]).order("created_at",{ascending:false}); const b=await supabase.from("role_permissions").select("role,resource,can_view,can_create,can_update,can_delete").order("resource"); if(a.error)setError(a.error.message); else setRows(a.data||[]); if(b.error)setError(b.error.message); else setPerms(b.data||[]);})();},[]);
 return <div className="admin-page"><div className="admin-page-head"><div><div className="admin-eyebrow">ACCESS / RBAC</div><h1>Users / Roles / Permissions</h1><p>Master Admin access control for the LE SHE SAREE control room.</p></div></div>{error&&<div className="admin-alert">{error}</div>}<section className="admin-card"><div className="admin-card-head"><div><h2>Administrators</h2><p>Master Admin controls activation and role assignment.</p></div></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Name</th><th>Role</th><th>Status</th><th>Created</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.full_name||"Unnamed admin"}</strong></td><td>{r.role}</td><td>{r.is_active?"ACTIVE":"INACTIVE"}</td><td>{new Date(r.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div></section><section className="admin-card"><div className="admin-card-head"><div><h2>Permissions Matrix</h2><p>Database-backed permissions for Admin and Master Admin.</p></div></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Module</th><th>View</th><th>Create</th><th>Update</th><th>Delete</th></tr></thead><tbody>{resources.map(x=>{const a=perms.find(p=>p.role==='admin'&&p.resource===x);const m=perms.find(p=>p.role==='master_admin'&&p.resource===x);return <tr key={x}><td><strong>{x.toUpperCase()}</strong></td><td>{a?.can_view?'✓':'—'}</td><td>{a?.can_create?'✓':'—'}</td><td>{a?.can_update?'✓':'—'}</td><td>{a?.can_delete?'✓':'—'}</td></tr>})}</tbody></table></div></section><section className="admin-card"><h2>Security boundary</h2><p>Role and activation changes are protected by database-side authorization. Admins must not modify their own role or access state. Permission administration is restricted to Master Admin by RLS.</p></section></div>;
}
