"use client";
import { FormEvent, useEffect, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase-browser";

const resources = ["products","categories","inventory","orders","customers","marketing","cms","settings"];
type AdminRow = { id:string; full_name:string|null; role:"admin"|"master_admin"; is_active:boolean; created_at:string };

export default function AdminUsersPage() {
 const supabase=getSupabaseBrowserClient();
 const [rows,setRows]=useState<AdminRow[]>([]); const [perms,setPerms]=useState<any[]>([]); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(false); const [email,setEmail]=useState(""); const [name,setName]=useState("");
 async function load(){ if(!supabase)return; const a=await supabase.from("profiles").select("id,full_name,role,is_active,created_at").in("role",["admin","master_admin"]).order("created_at",{ascending:false}); const b=await supabase.from("role_permissions").select("role,resource,can_view,can_create,can_update,can_delete").order("resource"); if(a.error)setError(a.error.message); else setRows((a.data||[]) as AdminRow[]); if(b.error)setError(b.error.message); else setPerms(b.data||[]); }
 useEffect(()=>{load();},[]);
 async function invite(e:FormEvent){e.preventDefault();setError("");setNotice("");setBusy(true);if(!supabase){setError("Store connection is not configured yet.");setBusy(false);return;}const {data,error:fnError}=await supabase.functions.invoke("admin-invite",{body:{email,name,full_name:name}});if(fnError||data?.error){setError(fnError?.message||data?.error||"Invitation failed.");}else{setNotice(`Invitation sent to ${email.trim().toLowerCase()}.`);setEmail("");setName("");await load();}setBusy(false);}
 async function changeRole(id:string,role:"admin"|"master_admin"){setError("");setNotice("");if(!supabase)return;const {error:e}=await supabase.rpc("set_admin_role",{p_user_id:id,p_role:role});if(e)setError(e.message);else{setNotice("Role updated successfully.");await load();}}
 async function changeActive(id:string,active:boolean){setError("");setNotice("");if(!supabase)return;const {error:e}=await supabase.rpc("set_admin_active",{p_user_id:id,p_active:active});if(e)setError(e.message);else{setNotice(active?"Admin activated.":"Admin deactivated.");await load();}}
 return <div className="admin-page"><div className="admin-page-head"><div><div className="admin-eyebrow">ACCESS / RBAC</div><h1>Users / Roles / Permissions</h1><p>Master Admin access control for the LE SHE SAREE control room.</p></div></div>{error&&<div className="admin-alert">{error}</div>}{notice&&<div className="admin-alert">{notice}</div>}
 <section className="admin-card"><div className="admin-card-head"><div><h2>Invite Administrator</h2><p>Only an active Master Admin can send an Admin invitation.</p></div></div><form onSubmit={invite} className="admin-form"><div className="form-row"><label>Full name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Administrator name"/></label><label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="admin@example.com"/></label></div><button className="checkout-button" type="submit" disabled={busy}>{busy?"SENDING…":"SEND ADMIN INVITE →"}</button></form></section>
 <section className="admin-card"><div className="admin-card-head"><div><h2>Administrators</h2><p>Master Admin controls activation and role assignment.</p></div></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Name</th><th>Role</th><th>Status</th><th>Created</th><th>Controls</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.full_name||"Unnamed admin"}</strong></td><td><select value={r.role} onChange={e=>changeRole(r.id,e.target.value as "admin"|"master_admin")} disabled={r.role==="master_admin"}><option value="admin">ADMIN</option><option value="master_admin">MASTER ADMIN</option></select></td><td>{r.is_active?"ACTIVE":"INACTIVE"}</td><td>{new Date(r.created_at).toLocaleDateString()}</td><td><button type="button" onClick={()=>changeActive(r.id,!r.is_active)} disabled={r.role==="master_admin"}>{r.is_active?"DEACTIVATE":"ACTIVATE"}</button></td></tr>)}</tbody></table></div></section>
 <section className="admin-card"><div className="admin-card-head"><div><h2>Permissions Matrix</h2><p>Database-backed permissions for Admin and Master Admin.</p></div></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Module</th><th>View</th><th>Create</th><th>Update</th><th>Delete</th></tr></thead><tbody>{resources.map(x=>{const a=perms.find(p=>p.role==='admin'&&p.resource===x);return <tr key={x}><td><strong>{x.toUpperCase()}</strong></td><td>{a?.can_view?'✓':'—'}</td><td>{a?.can_create?'✓':'—'}</td><td>{a?.can_update?'✓':'—'}</td><td>{a?.can_delete?'✓':'—'}</td></tr>})}</tbody></table></div></section>
 <section className="admin-card"><h2>Security boundary</h2><p>Role and activation changes are protected by database-side authorization. Admins cannot modify their own role or access state. Permission administration remains restricted to Master Admin.</p></section></div>;
}