"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase-browser";

type CartItem={product_id:string;slug:string;name:string;price:number;image_url:string|null;quantity:number;size:string};
type Campaign={name:string;code:string|null;discount_percent:number;starts_at:string|null;ends_at:string|null;is_active:boolean};

export default function CheckoutPage(){
 const [items,setItems]=useState<CartItem[]>([]);const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [coupon,setCoupon]=useState("");const [applied,setApplied]=useState<Campaign|null>(null);const [couponError,setCouponError]=useState("");const [submitted,setSubmitted]=useState(false);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{try{const raw=localStorage.getItem("leshe-bag-items");if(raw)setItems(JSON.parse(raw));}catch{} const supabase=getSupabaseBrowserClient();if(supabase)supabase.from("marketing_campaigns").select("name,code,discount_percent,starts_at,ends_at,is_active").eq("is_active",true).then(({data})=>setCampaigns((data||[]) as Campaign[]));},[]);
 const subtotal=useMemo(()=>items.reduce((sum,item)=>sum+item.price*item.quantity,0),[items]);
 const discount=applied?Math.min(subtotal,subtotal*Number(applied.discount_percent||0)/100):0;const total=subtotal-discount;
 function applyCoupon(){const code=coupon.trim().toUpperCase();setCouponError("");setApplied(null);if(!code)return;const now=Date.now();const match=campaigns.find(c=>c.code?.toUpperCase()===code&&(!c.starts_at||new Date(c.starts_at).getTime()<=now)&&(!c.ends_at||new Date(c.ends_at).getTime()>=now));if(!match){setCouponError("That promotion code is not active or could not be found.");return;}setApplied(match);}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");if(!items.length){setError("Your bag is empty. Please add a saree first.");return;}setBusy(true);const form=new FormData(event.currentTarget);const customerName=String(form.get("name")||"");const supabase=getSupabaseBrowserClient();if(!supabase){setError("Store connection is not configured yet.");setBusy(false);return;}const {data,error:rpcError}=await supabase.rpc("place_order_with_promo",{p_customer_name:customerName,p_email:String(form.get("email")||""),p_phone:String(form.get("phone")||""),p_address:String(form.get("address")||""),p_city:String(form.get("city")||""),p_pin_code:String(form.get("pin")||""),p_items:items.map(item=>({product_id:item.product_id,quantity:item.quantity,size:item.size})),p_promo_code:applied?.code||null});if(rpcError){setError(rpcError.message||"We couldn't place the order. Please try again.");setBusy(false);return;}const receipt=data as {id:string;receipt_token:string};if(!receipt?.id||!receipt?.receipt_token){setError("The order was created but the secure receipt could not be prepared. Please contact support.");setBusy(false);return;}const id=receipt.id;try{localStorage.setItem("leshe-last-order",JSON.stringify({id,receipt_token:receipt.receipt_token,customer_name:customerName,items:items.map(item=>({id:item.product_id,product_name:item.name,quantity:item.quantity,unit_price:item.price,size:item.size||null})),subtotal,shipping_fee:0,discount_code:applied?.code||null,discount_amount:discount,total,created_at:new Date().toISOString(),status:"pending",payment_status:"pending"}));}catch{} localStorage.removeItem("leshe-bag-items");localStorage.setItem("leshe-bag-count","0");setSubmitted(true);window.location.href=`/order/${id}?token=${encodeURIComponent(receipt.receipt_token)}`;}
 return <main className="checkout-shell"><header className="checkout-header"><a className="wordmark" href="/">LE SHE<br/><span>SAREE</span></a><a href="/bag">Bag ({items.reduce((s,i)=>s+i.quantity,0)})</a></header><section className="checkout-grid"><div className="checkout-intro"><span>03 — CHECKOUT</span><h1>MAKE IT<br/><i>YOURS.</i></h1><p>Complete your details and we'll prepare your order with care.</p><div className="checkout-total"><span>SUBTOTAL</span><strong>₹ {subtotal.toLocaleString("en-IN")}</strong>{applied&&<><span>PROMO / {applied.code}</span><strong>− ₹ {discount.toLocaleString("en-IN")}</strong></>}<span>ORDER TOTAL</span><strong>₹ {total.toLocaleString("en-IN")}</strong></div></div>{!submitted?<form className="checkout-form" onSubmit={submit}><div className="coupon-row"><input value={coupon} onChange={e=>setCoupon(e.target.value)} placeholder="PROMOTION CODE"/><button type="button" onClick={applyCoupon}>APPLY</button></div>{couponError&&<p className="form-error">{couponError}</p>}{applied&&<p className="form-success">{applied.code} applied — {applied.discount_percent}% off.</p>}<label>Full name<input required name="name" placeholder="Your name"/></label><label>Email<input required type="email" name="email" placeholder="you@example.com"/></label><label>Phone<input required name="phone" placeholder="+91"/></label><label>Address<textarea required name="address" placeholder="Delivery address" rows={3}/></label><div className="form-row"><label>City<input required name="city" placeholder="City"/></label><label>PIN code<input required name="pin" inputMode="numeric" placeholder="000000"/></label></div>{error&&<p className="form-error">{error}</p>}<button className="checkout-button" type="submit" disabled={busy||!items.length}><span>{busy?"PLACING ORDER…":"PLACE ORDER"}</span><b>→</b></button></form>:null}</section></main>
}
