"use client";

import { useEffect, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase-browser";

type Product={id:string;name:string;price:number;description:string|null;sizes:string[];stock:number;image_url:string|null;is_active:boolean;slug:string;material:string|null;care_instructions:string|null;seo_title:string|null;seo_description:string|null};
type GalleryImage={id:string;image_url:string;alt_text:string|null;display_order:number;is_primary:boolean};
type DisplayProduct=Product&{label:string;tone:string;desc:string};
type CartItem={product_id:string;slug:string;name:string;price:number;image_url:string|null;quantity:number;size:string};
const fallback:Record<string,DisplayProduct>={gulab:{id:"gulab",name:"Gulab Silk Saree",price:2499,description:null,sizes:["Free Size","Custom"],stock:10,image_url:null,is_active:true,slug:"gulab",material:"Silk blend",care_instructions:"Dry clean recommended",seo_title:null,seo_description:null,label:"GULAB",tone:"rose",desc:"A soft, expressive saree inspired by the quiet romance of Indian florals. Finished for an effortless drape."},noor:{id:"noor",name:"Noor Handloom Saree",price:2899,description:null,sizes:["Free Size","Custom"],stock:10,image_url:null,is_active:true,slug:"noor",material:"Handloom textile",care_instructions:"Gentle care recommended",seo_title:null,seo_description:null,label:"NOOR",tone:"stone",desc:"A handloom-inspired everyday classic with a calm texture and a modern, fluid silhouette."},madhubani:{id:"madhubani",name:"Madhubani Saree",price:3199,description:null,sizes:["Free Size","Custom"],stock:10,image_url:null,is_active:true,slug:"madhubani",material:"Artisan textile",care_instructions:"Dry clean recommended",seo_title:null,seo_description:null,label:"MADHU",tone:"plum",desc:"A richly expressive textile story with artisanal character and a contemporary edge."},meher:{id:"meher",name:"Meher Cotton Saree",price:2199,description:null,sizes:["Free Size","Custom"],stock:10,image_url:null,is_active:true,slug:"meher",material:"Cotton",care_instructions:"Gentle wash recommended",seo_title:null,seo_description:null,label:"MEHER",tone:"sand",desc:"Light, breathable and easy to wear, made for slow afternoons and everyday rituals."}};

export default function ProductPage({params}:{params:Promise<{slug:string}>}){
 const [product,setProduct]=useState<DisplayProduct>(fallback.gulab),[gallery,setGallery]=useState<GalleryImage[]>([]),[selectedImage,setSelectedImage]=useState<string|null>(null),[size,setSize]=useState("Free Size"),[added,setAdded]=useState(false),[bag,setBag]=useState(0),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;params.then(async({slug})=>{const local=fallback[slug]||fallback.gulab;if(active)setProduct(local);const s=getSupabaseBrowserClient();if(s){const {data}=await s.from("products").select("id,name,price,description,sizes,stock,image_url,is_active,slug,material,care_instructions,seo_title,seo_description").eq("slug",slug).eq("is_active",true).maybeSingle();if(data&&active){const live=data as Product;const sizes=live.sizes?.length?live.sizes:local.sizes;setProduct({...live,price:Number(live.price),label:live.name.split(" ")[0].toUpperCase(),tone:local.tone,desc:live.description||local.desc,sizes,stock:Number(live.stock||0)});setSize(sizes[0]||"Free Size");const {data:images}=await s.from("product_images").select("id,image_url,alt_text,display_order,is_primary").eq("product_id",live.id).order("display_order",{ascending:true});if(active&&images?.length){setGallery(images as GalleryImage[]);setSelectedImage((images.find((i:GalleryImage)=>i.is_primary)||images[0]).id);}}}if(active){setBag(Number(localStorage.getItem("leshe-bag-count")||0));setLoading(false)}});return()=>{active=false}},[params]);
 const image=gallery.find(x=>x.id===selectedImage)?.image_url||product.image_url;
 const add=()=>{if(product.stock<=0)return;const raw=localStorage.getItem("leshe-bag-items");const items:CartItem[]=raw?JSON.parse(raw):[];const index=items.findIndex(item=>item.product_id===product.id&&item.size===size);if(index>=0)items[index].quantity=Math.min(items[index].quantity+1,product.stock);else items.push({product_id:product.id,slug:product.slug,name:product.name,price:product.price,image_url:product.image_url,quantity:1,size});const total=items.reduce((sum,item)=>sum+item.quantity,0);localStorage.setItem("leshe-bag-items",JSON.stringify(items));localStorage.setItem("leshe-bag-count",String(total));window.dispatchEvent(new Event("storage"));setBag(total);setAdded(true);setTimeout(()=>setAdded(false),900)};
 return <main className={`product-page tone-${product.tone}`}><header className="topbar product-top"><a className="wordmark" href="/">LE SHE<br/><span>SAREE</span></a><nav><a href="/">Shop</a><a href="/bag">Bag ({bag})</a></nav><span className="top-meta">PRODUCT / {product.slug.toUpperCase()}</span></header><a className="back-link" href="/">← Back to collection</a><section className="product-detail"><div className="product-visual"><div><div className="product-art" style={image?{backgroundImage:`url(${image})`,backgroundSize:"cover",backgroundPosition:"center"}:undefined}><span>{product.label}</span><small>LE SHE SAREE</small></div>{gallery.length>1&&<div className="product-thumbs" aria-label="Product images">{gallery.map(item=><button type="button" key={item.id} className={selectedImage===item.id?"selected":""} onClick={()=>setSelectedImage(item.id)}><img src={item.image_url} alt={item.alt_text||product.name}/></button>)}</div>}</div></div><div className="product-info"><p className="eyebrow">HANDCRAFTED INDIA / 2026</p><h1>{product.name}</h1><div className="price">₹ {product.price.toLocaleString("en-IN")}</div><p className="description">{product.desc}</p>{product.material&&<p className="product-material"><b>MATERIAL</b> {product.material}</p>}<div className="option-label">SIZE <span>{size}</span></div><div className="sizes">{product.sizes.map(s=><button type="button" className={size===s?"selected":""} onClick={()=>setSize(s)} key={s}>{s}</button>)}</div><button className={`add-button ${added?"added":""}`} disabled={loading||product.stock<=0} onClick={add}>{loading?"LOADING…":product.stock<=0?"OUT OF STOCK":added?"ADDED TO BAG ✓":"ADD TO BAG"}<span>↗</span></button><div className="details"><p>{product.care_instructions||"Handcrafted textile · Gentle care recommended"}</p><p>{product.stock>0?`${product.stock} available`:"Currently unavailable"}</p><p>Shipping calculated at checkout</p></div></div></section></main>;
}
