"use client";

import { FormEvent, useEffect, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase-browser";

type Review={id:string;customer_name:string;rating:number;title:string|null;body:string;is_verified:boolean;admin_reply:string|null;created_at:string};

export default function ProductReviews({productId}:{productId:string}){
 const [reviews,setReviews]=useState<Review[]>([]),[rating,setRating]=useState(5),[title,setTitle]=useState(""),[body,setBody]=useState(""),[name,setName]=useState(""),[email,setEmail]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[showForm,setShowForm]=useState(false);
 useEffect(()=>{const s=getSupabaseBrowserClient();if(s)s.from("reviews").select("id,customer_name,rating,title,body,is_verified,admin_reply,created_at").eq("product_id",productId).eq("status","approved").order("created_at",{ascending:false}).then(({data})=>setReviews((data||[])as Review[]))},[productId]);
 async function submit(e:FormEvent){e.preventDefault();const s=getSupabaseBrowserClient();if(!s)return;setBusy(true);setMessage("");const {data:{user}}=await s.auth.getUser();if(!user){setMessage("Please sign in from your account before submitting a review.");setBusy(false);return}const {data,error}=await s.from("reviews").insert({product_id:productId,customer_id:user.id,customer_name:name.trim()||user.email?.split("@")[0]||"Customer",customer_email:email.trim()||user.email,rating,title:title.trim()||null,body:body.trim(),status:"pending"}).select("id,customer_name,rating,title,body,is_verified,admin_reply,created_at").single();if(error)setMessage(error.message);else{setMessage("Thank you. Your review has been submitted for approval.");setReviews(x=>x);setTitle("");setBody("");setShowForm(false)}setBusy(false);void data}
 const average=reviews.length?reviews.reduce((a,r)=>a+r.rating,0)/reviews.length:0;
 return <section className="reviews-section"><div className="section-head"><span>REVIEWS / {reviews.length}</span><span>{reviews.length?`${average.toFixed(1)} ★ AVERAGE`:"NO REVIEWS YET"}</span></div><div className="reviews-list">{reviews.map(r=><article className="review-card" key={r.id}><div className="review-top"><strong>{"★".repeat(r.rating)}{"☆".repeat(5-r.rating)}</strong><span>{r.is_verified?"VERIFIED PURCHASE · ":""}{new Date(r.created_at).toLocaleDateString("en-IN")}</span></div><h3>{r.title||"A customer's note"}</h3><p>{r.body}</p><small>— {r.customer_name}</small>{r.admin_reply&&<div className="review-reply"><b>LE SHE SAREE</b><p>{r.admin_reply}</p></div>}</article>)}</div><button className="add-button review-toggle" onClick={()=>setShowForm(x=>!x)}>{showForm?"CLOSE REVIEW FORM":"WRITE A REVIEW"}<span>↗</span></button>{showForm&&<form className="review-form" onSubmit={submit}><div className="review-stars">{[1,2,3,4,5].map(n=><button type="button" key={n} aria-label={`${n} stars`} className={n<=rating?"selected":""} onClick={()=>setRating(n)}>★</button>)}</div><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Review title"/><textarea required minLength={5} value={body} onChange={e=>setBody(e.target.value)} placeholder="Tell us about your experience…" rows={5}/><button disabled={busy} className="admin-primary" type="submit">{busy?"SUBMITTING…":"SUBMIT REVIEW →"}</button>{message&&<p>{message}</p>}</form>}</section>
}
