"use client";

import { useEffect, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase-browser";

type Order={id:string;customer_name:string;status:string;payment_status:string;subtotal:number;shipping_fee:number;total:number;created_at:string};
type Item={id:string;product_name:string;quantity:number;unit_price:number;size:string|null};

export default function OrderPage({params}:{params:Promise<{id:string}>}){
 const [order,setOrder]=useState<Order|null>(null);const [items,setItems]=useState<Item[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 useEffect(()=>{let active=true;params.then(async({id})=>{const supabase=getSupabaseBrowserClient();if(!supabase){setError("Store connection is not configured yet.");setLoading(false);return;}const {data,error:orderError}=await supabase.from("orders").select("id,customer_name,status,payment_status,subtotal,shipping_fee,total,created_at").eq("id",id).maybeSingle();if(orderError||!data){setError("We couldn't find this order.");setLoading(false);return;}const {data:itemData}=await supabase.from("order_items").select("id,product_name,quantity,unit_price,size").eq("order_id",id).order("created_at");if(active){setOrder(data as Order);setItems((itemData||[]) as Item[]);setLoading(false);}});return()=>{active=false}},[params]);
 const money=(v:number)=>`₹ ${Number(v||0).toLocaleString("en-IN")}`;
 return <main className="checkout-shell"><header className="checkout-header"><a className="wordmark" href="/">LE SHE<br/><span>SAREE</span></a><a href="/">Shop</a></header><section className="order-receipt">{loading?<div className="order-success"><span>ORDER / LOADING</span><h2>ONE<br/><i>MOMENT.</i></h2></div>:error?<div className="order-success"><span>ORDER / NOT FOUND</span><h2>WE'RE<br/><i>SORRY.</i></h2><p>{error}</p><a href="/">Continue shopping →</a></div>:order?<><div className="receipt-head"><span>ORDER / CONFIRMED</span><small>{new Date(order.created_at).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"})}</small></div><h1>THANK<br/><i>{order.customer_name.split(" ")[0]}.</i></h1><p className="receipt-note">Your order is safely in our system. We'll prepare your pieces with care and contact you for confirmation.</p><div className="receipt-id"><span>ORDER ID</span><strong>{order.id.toUpperCase()}</strong></div><div className="receipt-items">{items.map(item=><div key={item.id}><span>{item.product_name}<small>{item.size||"Free Size"} · ×{item.quantity}</small></span><strong>{money(item.unit_price*item.quantity)}</strong></div>)}</div><div className="receipt-total"><span>SUBTOTAL</span><strong>{money(order.subtotal)}</strong><span>SHIPPING</span><strong>{money(order.shipping_fee)}</strong><span>TOTAL</span><strong>{money(order.total)}</strong></div><div className="receipt-status"><span>ORDER STATUS</span><b>{order.status.toUpperCase()}</b><span>PAYMENT</span><b>{order.payment_status.toUpperCase()}</b></div><a className="checkout-button" href="/">CONTINUE SHOPPING <span>↗</span></a></>:null}</section></main>
}
