"use client";
import {useEffect,useMemo,useState} from "react";
import {getSupabaseBrowserClient} from "@/lib/supabase-browser";
type Review={id:string;product_id:string;customer_name:string;rating:number;title:string|null;body:string;is_verified:boolean;status:string;admin_reply:string|null;created_at:string};
const states=["all","pending","approved","rejected"];
export default function ReviewsPage(){const[r,setR]=useState<Review[]>([]),[filter,setFilter]=useState("all"),[q,setQ]=useState(""),[selected,setSelected]=useState<Review|null>(null),[reply,setReply]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(){const s=getSupabaseBrowserClient();if(!s){setError("SUPABASE CONNECTION IS NOT CONFIGURED.");setLoading(false);return}setLoading(true);const{data,error:e}=await s.from("reviews").select("id,product_id,customer_name,rating,title,body,is_verified,status,admin_reply,created_at").order("created_at",{ascending:false});if(e)setError(e.message);else setR((data||[])as Review[]);setLoading(false)}
 useEffect(()=>{load()},[]);const visible=useMemo(()=>{const x=q.trim().toLowerCase();return r.filter(v=>(filter==="all"||v.status===filter)&&(!x||v.customer_name.toLowerCase().includes(x)||(v.title||"").toLowerCase().includes(x)||v.body.toLowerCase().includes(x)||v.product_id.toLowerCase().includes(x)))},[r,filter,q]);const avg=r.length?r.reduce((a,x)=>a+x.rating,0)/r.length:0;
 async function moderate(status:string){if(!selected)return;const s=getSupabaseBrowserClient();if(!s)return;setBusy(true);const{data,error:e}=await s.from("reviews").update({status,updated_at:new Date().toISOString()}).eq("id",selected.id).select("id,product_id,customer_name,rating,title,body,is_verified,status,admin_reply,created_at").single();if(e)setError(e.message);else{setR(x=>x.map(v=>v.id===selected.id?data as Review:v));setSelected(data as Review)}setBusy(false)}
 async function saveReply(){if(!selected)return;const s=getSupabaseBrowserClient();if(!s)return;setBusy(true);const{data,error:e}=await s.from("reviews").update({admin_reply:reply.trim()||null,replied_at:reply.trim()?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq("id",selected.id).select("id,product_id,customer_name,rating,title,body,is_verified,status,admin_reply,created_at").single();if(e)setError(e.message);else{setR(x=>x.map(v=>v.id===selected.id?data as Review:v));setSelected(data as Review)}setBusy(false)}
 return <div className="admin-page"><header className="admin-page-head"><div><span className="admin-eyebrow">08 — REVIEWS</span><h1>Voice <i>of the wearer.</i></h1><p>Moderate ratings, publish trusted reviews and respond from one place.</p></div><button className="admin-action" onClick={load}>REFRESH ↻</button></header><section className="stat-grid"><div className="stat-card"><strong>{r.length}</strong><span>Total reviews</span></div><div className="stat-card"><strong>{r.filter(x=>x.status==='pending').length}</strong><span>Pending</span></div><div className="stat-card"><strong>{r.filter(x=>x.status==='approved').length}</strong><span>Published</span></div><div className="stat-card"><strong>{avg.toFixed(1)} ★</strong><span>Average rating</span></div></section><div className="admin-toolbar"><input className="admin-search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search reviewer, title, text or product ID…"/></div><div className="admin-tabs">{states.map(s=><button key={s} className={filter===s?"active":""} onClick={()=>setFilter(s)}>{s.toUpperCase()}</button>)}</div>{error&&<div className="admin-notice">{error}</div>}{loading?<div className="admin-empty">LOADING REVIEWS…</div>:visible.length===0?<div className="admin-empty"><h2>No reviews here.</h2><p>New customer reviews will appear after submission.</p></div>:<div className="customer-panel">{visible.map(x=><button className="customer-row" key={x.id} onClick={()=>{setSelected(x);setReply(x.admin_reply||"")}}><div><strong>{"★".repeat(x.rating)}{"☆".repeat(5-x.rating)} {x.title||"Untitled review"}</strong><small>{x.customer_name} · {x.is_verified?"Verified purchase · ":""}{new Date(x.created_at).toLocaleDateString("en-IN")}</small></div><span>{x.status.toUpperCase()}</span></button>)}</div>}{selected&&<div className="order-drawer-backdrop" onClick={()=>setSelected(null)}><aside className="order-drawer" onClick={e=>e.stopPropagation()}><button className="drawer-close" onClick={()=>setSelected(null)}>CLOSE ×</button><span className="admin-eyebrow">REVIEW / {selected.id.slice(0,8).toUpperCase()}</span><h2>{"★".repeat(selected.rating)}{"☆".repeat(5-selected.rating)}</h2><div className="drawer-meta"><p><strong>{selected.title||"Untitled review"}</strong></p><p>{selected.customer_name} · {selected.is_verified?"Verified purchase":"Customer review"}</p><p>Product ID: {selected.product_id}</p><p>{selected.body}</p></div><div className="drawer-status"><label>MODERATION<select value={selected.status} disabled={busy} onChange={e=>moderate(e.target.value)}>{states.filter(x=>x!=="all").map(s=><option key={s} value={s}>{s.toUpperCase()}</option>)}</select></label></div><label className="review-reply">ADMIN REPLY<textarea rows={5} value={reply} onChange={e=>setReply(e.target.value)} placeholder="Write a helpful response…"/></label><button className="admin-primary" disabled={busy} onClick={saveReply}>{busy?"SAVING…":"SAVE REPLY →"}</button></aside></div>}</div>}
